In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
a = np.arange(1, 201)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [6]:
b = np.arange(500,800)
b

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564,
       565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577,
       578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590,
       591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603,
       604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616,
       617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629,
       630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642,
       643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655,
       656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668,
       669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 68

In [7]:
train_test_split(a)

[array([148, 129, 174, 134, 145,  14,  76,  68, 115,  98,  33, 157,  10,
         32, 192, 155, 188,   6, 179, 142, 167, 190, 126, 139, 186, 108,
         88, 125,  46,  45,  90,  67, 196,  27, 189,  72,  40,  35,  71,
        178, 114,   8,  83,  51,  38,  37, 159,  73,  86,  78,   7, 121,
        105,   3, 195,  97, 113,  12, 166, 104,  29, 187, 156, 163, 136,
         59,  56,  41,  30, 194, 135, 152,  64, 175,  92, 103, 182, 200,
        107, 198,  87,  74,  57,  63, 161, 106,  85,  84, 171,  77, 112,
        144,  17, 128, 147,  15,  94,  13,  66,  91, 111,  75, 143, 176,
        132, 154, 153, 191,  69,  93, 146,  52, 185,  81,  61,  80, 184,
         28,  21,  47,  95, 197,  26,  82, 158,  11, 137,   1, 183, 168,
        122,  22,  79, 124, 138, 140, 100,  42,   5, 116,  54,  48,  20,
        150,  24,  99,  65,  34, 110,  19]),
 array([164, 177, 141, 101, 193, 133, 151, 102,  96, 160, 165, 170,  31,
        162, 127,  25,  16, 119, 120,   9, 123, 149,   4,  18,  53, 118,
      

In [8]:
a_train, a_test = train_test_split(a)

In [10]:
a_train.shape, a_test.shape

((150,), (50,))